name: Deploy URL Shortener

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this if needed

      - name: Deploy Lambda Function
        run: |
          cd lambda
          zip -r ../lambda.zip .
          cd ..
          aws lambda update-function-code --function-name your-lambda-name --zip-file fileb://lambda.zip

      - name: Deploy Frontend to S3
        run: aws s3 sync frontend/ s3://url-shortener-frontend/ --delete
